- name: Kafka | Make sure kafka is not running under supervisord
  supervisorctl: name=kafka state=stopped
  sudo: yes

- include: dependencies.yml
- include: user.yml
- include: install.yml
- include: configure.yml
- include: supervise_broker.yml
