---
- name: 3. Create a new database
  mysql_db: name=test state=present collation=utf8_general_ci

- name: 4. Create a database user
  mysql_user: name=test password=test priv=*.*:ALL host=localhost state=present

- name: 5a. Copy sample data
  copy: src=dump.sql dest=/tmp/dump.sql

- name: 5b. Insert sample data
  shell: cat /tmp/dump.sql | mysql -u test -pdemo test
